# Generated by Django 4.1 on 2022-09-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_is_cancelled_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='from_account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_accounts',
            field=models.ManyToManyField(related_name='outcomes', to='transactions.account'),
        ),
    ]
